steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/project-nodeapp-docker/project-nodeapp-docker:latest',
      '.'
    ]

# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/project-nodeapp-docker/project-nodeapp-docker:latest'
    ]

# Step 3: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'gcloud'
  args:
    [
      'run', 'deploy', 'project-nodeapp-docker',
      '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/project-nodeapp-docker/project-nodeapp-docker:latest',
      '--platform', 'managed',
      '--region', '${_REGION}',                        # Substitution variable
      '--service-account', '503184524416-compute@developer.gserviceaccount.com',
      '--allow-unauthenticated',
      '--set-env-vars',
      'MONGO_URI=mongodb+srv://admin:admin@nodeappcrud.hck03x6.mongodb.net/sample_mflix?appName=nodeappCRUD,ENV=production,JWT_SECRET=12345qwerty54321'
    ]

# Optional: Timeout if your build takes longer
timeout: '1200s'  # 20 minutes

# Substitutions (variables you can override in trigger)
substitutions:
  _REGION: 'asia-south1'