steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/project-nodeapp-docker/project-nodeapp-docker:latest',
      '.'
    ]

# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/project-nodeapp-docker/project-nodeapp-docker:latest'
    ]

# Step 3: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'gcloud'
  args:
    [
      'run', 'deploy', 'project-nodeapp-docker',
      '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/project-nodeapp-docker/project-nodeapp-docker:latest',
      '--platform', 'managed',
      '--region', '${_REGION}',
      '--service-account', '503184524416-compute@developer.gserviceaccount.com',
      '--allow-unauthenticated'
      
    ]

# Top-level options
options:
  logging: CLOUD_LOGGING_ONLY   # Fixes the "build.service_account" logs issue

# Optional: Timeout if your build takes longer
timeout: '1200s'  # 20 minutes

# Substitutions (you can override in trigger)
substitutions:
  _REGION: 'asia-south1'